// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACok9fsjgvv8aZ_NpJ_UJP7j2zH1D6jqQ',
    appId: '1:939750710622:web:cb61f1e243e812530603cf',
    messagingSenderId: '939750710622',
    projectId: 'flutter-chat-app-cc9a0',
    authDomain: 'flutter-chat-app-cc9a0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cc9a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVn4qD-nxHr9_Xz1A_BNoBcWTzAN-uJ8Y',
    appId: '1:939750710622:android:5d12452827860b100603cf',
    messagingSenderId: '939750710622',
    projectId: 'flutter-chat-app-cc9a0',
    storageBucket: 'flutter-chat-app-cc9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQtUuLk-9eMD7LDDFnxDVlviUgBwyXkw',
    appId: '1:939750710622:ios:39848197307e8f650603cf',
    messagingSenderId: '939750710622',
    projectId: 'flutter-chat-app-cc9a0',
    storageBucket: 'flutter-chat-app-cc9a0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQtUuLk-9eMD7LDDFnxDVlviUgBwyXkw',
    appId: '1:939750710622:ios:e029f9280ccb25cc0603cf',
    messagingSenderId: '939750710622',
    projectId: 'flutter-chat-app-cc9a0',
    storageBucket: 'flutter-chat-app-cc9a0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
